<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P3A-HQ3PXJ2" ignored="1" name="Smoke" tests="19" failures="3" timestamp="23 Sep 2019 04:37:27 GMT" time="18.853" errors="0">
  <testcase name="test2" time="0.012" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="test3" time="0.011" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="test1" time="0.014" classname="testngFeatures.DemoAssertion1">
    <failure type="java.lang.AssertionError" message="expected [GoodBye] but found [Bye]">
      <![CDATA[java.lang.AssertionError: expected [GoodBye] but found [Bye]
at testngFeatures.DemoAssertion1.test1(DemoAssertion1.java:9)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="Test6" time="0.013" classname="testngFeatures.DemoAssertion1">
    <failure type="java.lang.AssertionError" message="Failing">
      <![CDATA[java.lang.AssertionError: Failing
at testngFeatures.DemoAssertion1.Test6(DemoAssertion1.java:35)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- Test6 -->
  <testcase name="Test5" time="0.019" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="test4" time="0.007" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="f" time="0.005" classname="testngFeatures.DemoDataProvider"/>
  <testcase name="f" time="0.001" classname="testngFeatures.DemoDataProvider"/>
  <testcase name="f" time="0.002" classname="testngFeatures.NewTest"/>
  <testcase name="f" time="0.029" classname="testngFeatures.DemoSoftAssert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [12] but found [10],
	Error expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [12] but found [10],
Error expected [true] but found [false]
at testngFeatures.DemoSoftAssert.f(DemoSoftAssert.java:17)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.009" classname="testngFeatures.DemoDataProvider"/>
  <testcase name="f" time="0.017" classname="testngFeatures.ExecutionSequence"/>
  <testcase name="f" time="7.314" classname="testngFeatures.OpenMercury"/>
  <testcase name="openBrowser" time="0.001" classname="testngFeatures.MercuryApplication"/>
  <testcase name="openURL" time="0.001" classname="testngFeatures.MercuryApplication"/>
  <testcase name="Login" time="0.001" classname="testngFeatures.MercuryApplication"/>
  <testcase name="searchFlight" time="0.001" classname="testngFeatures.MercuryApplication"/>
  <testcase name="logout" time="0.001" classname="testngFeatures.MercuryApplication"/>
  <testcase name="closeBrowser" time="0.001" classname="testngFeatures.MercuryApplication"/>
  <testcase name="bookFlight" time="0.0" classname="testngFeatures.MercuryApplication">
    <ignored/>
  </testcase> <!-- bookFlight -->
</testsuite> <!-- Smoke -->
