<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="P3A-HQ3PXJ2" name="testngFeatures.DemoAssertion1" tests="6" failures="2" timestamp="23 Sep 2019 04:37:27 GMT" time="0.076" errors="0">
  <testcase name="Test6" time="0.013" classname="testngFeatures.DemoAssertion1">
    <failure type="java.lang.AssertionError" message="Failing">
      <![CDATA[java.lang.AssertionError: Failing
at org.testng.Assert.fail(Assert.java:96)
at testngFeatures.DemoAssertion1.Test6(DemoAssertion1.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Test6 -->
  <testcase name="test1" time="0.014" classname="testngFeatures.DemoAssertion1">
    <failure type="java.lang.AssertionError" message="expected [GoodBye] but found [Bye]">
      <![CDATA[java.lang.AssertionError: expected [GoodBye] but found [Bye]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testngFeatures.DemoAssertion1.test1(DemoAssertion1.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.012" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="Test5" time="0.019" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="test4" time="0.007" classname="testngFeatures.DemoAssertion1"/>
  <testcase name="test3" time="0.011" classname="testngFeatures.DemoAssertion1"/>
</testsuite> <!-- testngFeatures.DemoAssertion1 -->
